//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoveTap.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHINHANH
    {
        public string MACN { get; set; }
        public string TENCN { get; set; }
        public string DIACHI { get; set; }
        public string MAADMIN { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
