//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoveTap.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTSP
    {
        public string MASP { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string HD { get; set; }
        public string VGA { get; set; }
        public string SCREENSIZE { get; set; }
        public string OS { get; set; }
        public string COLOR { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
