//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoveTap.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string USERPASS { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
