//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoveTap.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONKHO
    {
        public int MAKHO { get; set; }
        public int MASP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        public virtual KHO KHO { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
